//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
[System.Xml.Serialization.XmlRootAttribute("price-quotes", Namespace="http://www.canadapost.ca/ws/ship/rate-v4", IsNullable=false)]
public partial class pricequotes {
    
    private pricequotesPricequote[] pricequoteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("price-quote")]
    public pricequotesPricequote[] pricequote {
        get {
            return this.pricequoteField;
        }
        set {
            this.pricequoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequote {
    
    private string servicecodeField;
    
    private pricequotesPricequoteServicelink servicelinkField;
    
    private string servicenameField;
    
    private pricequotesPricequotePricedetails pricedetailsField;
    
    private object weightdetailsField;
    
    private pricequotesPricequoteServicestandard servicestandardField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-code")]
    public string servicecode {
        get {
            return this.servicecodeField;
        }
        set {
            this.servicecodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-link")]
    public pricequotesPricequoteServicelink servicelink {
        get {
            return this.servicelinkField;
        }
        set {
            this.servicelinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-name")]
    public string servicename {
        get {
            return this.servicenameField;
        }
        set {
            this.servicenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("price-details")]
    public pricequotesPricequotePricedetails pricedetails {
        get {
            return this.pricedetailsField;
        }
        set {
            this.pricedetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weight-details")]
    public object weightdetails {
        get {
            return this.weightdetailsField;
        }
        set {
            this.weightdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service-standard")]
    public pricequotesPricequoteServicestandard servicestandard {
        get {
            return this.servicestandardField;
        }
        set {
            this.servicestandardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequoteServicelink {
    
    private string relField;
    
    private string hrefField;
    
    private string mediatypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("media-type")]
    public string mediatype {
        get {
            return this.mediatypeField;
        }
        set {
            this.mediatypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetails {
    
    private decimal baseField;
    
    private pricequotesPricequotePricedetailsTaxes taxesField;
    
    private decimal dueField;
    
    private pricequotesPricequotePricedetailsOptions optionsField;
    
    private pricequotesPricequotePricedetailsAdjustments adjustmentsField;
    
    /// <remarks/>
    public decimal @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsTaxes taxes {
        get {
            return this.taxesField;
        }
        set {
            this.taxesField = value;
        }
    }
    
    /// <remarks/>
    public decimal due {
        get {
            return this.dueField;
        }
        set {
            this.dueField = value;
        }
    }
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsOptions options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsAdjustments adjustments {
        get {
            return this.adjustmentsField;
        }
        set {
            this.adjustmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsTaxes {
    
    private pricequotesPricequotePricedetailsTaxesGst gstField;
    
    private decimal pstField;
    
    private decimal hstField;
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsTaxesGst gst {
        get {
            return this.gstField;
        }
        set {
            this.gstField = value;
        }
    }
    
    /// <remarks/>
    public decimal pst {
        get {
            return this.pstField;
        }
        set {
            this.pstField = value;
        }
    }
    
    /// <remarks/>
    public decimal hst {
        get {
            return this.hstField;
        }
        set {
            this.hstField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsTaxesGst {
    
    private decimal percentField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsOptions {
    
    private pricequotesPricequotePricedetailsOptionsOption optionField;
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsOptionsOption option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsOptionsOption {
    
    private string optioncodeField;
    
    private string optionnameField;
    
    private byte optionpriceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-code")]
    public string optioncode {
        get {
            return this.optioncodeField;
        }
        set {
            this.optioncodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-name")]
    public string optionname {
        get {
            return this.optionnameField;
        }
        set {
            this.optionnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-price")]
    public byte optionprice {
        get {
            return this.optionpriceField;
        }
        set {
            this.optionpriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsAdjustments {
    
    private pricequotesPricequotePricedetailsAdjustmentsAdjustment adjustmentField;
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsAdjustmentsAdjustment adjustment {
        get {
            return this.adjustmentField;
        }
        set {
            this.adjustmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsAdjustmentsAdjustment {
    
    private string adjustmentcodeField;
    
    private string adjustmentnameField;
    
    private decimal adjustmentcostField;
    
    private pricequotesPricequotePricedetailsAdjustmentsAdjustmentQualifier qualifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjustment-code")]
    public string adjustmentcode {
        get {
            return this.adjustmentcodeField;
        }
        set {
            this.adjustmentcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjustment-name")]
    public string adjustmentname {
        get {
            return this.adjustmentnameField;
        }
        set {
            this.adjustmentnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjustment-cost")]
    public decimal adjustmentcost {
        get {
            return this.adjustmentcostField;
        }
        set {
            this.adjustmentcostField = value;
        }
    }
    
    /// <remarks/>
    public pricequotesPricequotePricedetailsAdjustmentsAdjustmentQualifier qualifier {
        get {
            return this.qualifierField;
        }
        set {
            this.qualifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequotePricedetailsAdjustmentsAdjustmentQualifier {
    
    private decimal percentField;
    
    /// <remarks/>
    public decimal percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.canadapost.ca/ws/ship/rate-v4")]
public partial class pricequotesPricequoteServicestandard {
    
    private bool amdeliveryField;
    
    private bool guaranteeddeliveryField;
    
    private byte expectedtransittimeField;
    
    private System.DateTime expecteddeliverydateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("am-delivery")]
    public bool amdelivery {
        get {
            return this.amdeliveryField;
        }
        set {
            this.amdeliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guaranteed-delivery")]
    public bool guaranteeddelivery {
        get {
            return this.guaranteeddeliveryField;
        }
        set {
            this.guaranteeddeliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-transit-time")]
    public byte expectedtransittime {
        get {
            return this.expectedtransittimeField;
        }
        set {
            this.expectedtransittimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected-delivery-date", DataType="date")]
    public System.DateTime expecteddeliverydate {
        get {
            return this.expecteddeliverydateField;
        }
        set {
            this.expecteddeliverydateField = value;
        }
    }
}
